# Generated by Django 5.2.17 on 2026-09-29 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_serviceheartbeat'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('general', models.JSONField(default=dict)),
                ('equipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.equipment')),
                ('legacy_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
            options={
                'db_table': 'robot',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'scenario',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250, unique=True)),
                ('location', models.TextField()),
                ('site', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(max_length=30)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'source',
            },
        ),
        migrations.CreateModel(
            name='CleaningSpec',
            fields=[
                ('robot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='workflow.robot')),
                ('values', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'cleaning_spec',
            },
        ),
        migrations.CreateModel(
            name='WarehouseSpec',
            fields=[
                ('robot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='workflow.robot')),
                ('values', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'warehouse_spec',
            },
        ),
        migrations.CreateModel(
            name='SourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('stored_path', models.TextField()),
                ('content', models.BinaryField()),
                ('acquired_at', models.DateTimeField(null=True)),
                ('processed_at', models.DateTimeField(null=True)),
                ('parser_version', models.CharField(max_length=160)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='workflow.source')),
            ],
            options={
                'db_table': 'source_snapshot',
            },
        ),
        migrations.CreateModel(
            name='RobotOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('supplier', models.CharField(blank=True, max_length=300)),
                ('terms', models.JSONField(default=dict)),
                ('review_state', models.CharField(default='unreviewed', max_length=20)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.robot')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.sourcesnapshot')),
            ],
            options={
                'db_table': 'robot_offer',
            },
        ),
        migrations.CreateModel(
            name='ReviewIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('field', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField()),
                ('evidence', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='open', max_length=20)),
                ('robot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.robot')),
                ('snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.sourcesnapshot')),
            ],
            options={
                'db_table': 'review_issue',
            },
        ),
        migrations.CreateModel(
            name='FieldObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('field', models.CharField(max_length=100)),
                ('raw_text', models.TextField()),
                ('normalized', models.JSONField(null=True)),
                ('evidence', models.JSONField(default=dict)),
                ('extraction_state', models.CharField(max_length=30)),
                ('review_state', models.CharField(default='unreviewed', max_length=20)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_observations', to='workflow.robot')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.sourcesnapshot')),
            ],
            options={
                'db_table': 'field_observation',
            },
        ),
        migrations.CreateModel(
            name='FieldSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('decision', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('current', models.BooleanField(default=False)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.fieldobservation')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.robot')),
            ],
            options={
                'db_table': 'field_selection',
                'constraints': [models.UniqueConstraint(condition=models.Q(('current', True)), fields=('robot', 'field'), name='one_current_field_selection')],
            },
        ),
        migrations.CreateModel(
            name='RobotScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='unreviewed', max_length=20)),
                ('evidence', models.JSONField(default=dict)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.robot')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.scenario')),
            ],
            options={
                'db_table': 'robot_scenario',
                'constraints': [models.UniqueConstraint(fields=('robot', 'scenario'), name='robot_scenario_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='sourcesnapshot',
            constraint=models.UniqueConstraint(fields=('source', 'sha256', 'parser_version'), name='source_version_unique'),
        ),
        migrations.AddIndex(
            model_name='fieldobservation',
            index=models.Index(fields=['robot', 'field', 'review_state'], name='field_obser_robot_i_951884_idx'),
        ),
    ]
