# Generated by Django 5.2.17 on 2026-09-29 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_preserve_existing_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewissue',
            name='resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reviewissue',
            name='resolved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reviewissue',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldobservation',
            name='review_state',
            field=models.CharField(choices=[('unreviewed', 'Ожидает проверки'), ('accepted', 'Подтверждено'), ('rejected', 'Отклонено')], default='unreviewed', max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('review', 'На проверке'), ('error', 'Ошибка')], default='pending', max_length=30),
        ),
    ]
